name: checkoutAction
on: [push]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: ls -lrt
      - name: checkout kro
        uses: actions/checkout@v3
      - name: after checkout
        run: ls -lrt

  