name: matrix
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample_variable_h_ye_node_version: [10, 13, 14]
    steps:
      - name: check node version before running matrix
        run: node -v
      - name: use the action
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.sample_variable_h_ye_node_version }}
      - name: check node version before running matrix
        run: node -v

