name: testingParallel
on: [push]
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: print hi
        run: echo "Hi.This is the first job's first step "
      - name: print hello
        run: echo "Hello.This is the first job's 2nd step."
  secondJob:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  thirdjob:
    runs-on: windows-latest
    needs: firstJob
    steps:
      - name: print a string
        run: Write-Output "Windows machine h ye"

# by default jobs parallely run krti h.. if you want to make them run sequentially then
# for dependnet jobs/sequential Jobs, use "needs"..so upr eg me phle first job chlegi phr third job
# agr firstjob fail ho jaae to thirdjob to start bhi ni hogi
