name: testingParallel
on: [push]
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: print hi
        run: echo "Hi.This is the first job's first step "
      - name: print hello
        run: echo "Hello.This is the first job's 2nd step"
  secondJob:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  thirdjob:
    runs-on: windows-latest
    needs: firstJob
    steps:
      - name: print a string
        run: Write-Output "Windows machine h ye"


