name: eventWorkflowDispatch
on: 
  workflow_dispatch:
    inputs:
      anyVariableNameIsmeValueStoreHogiIsInputKi:
        description: please select a environment     # jo UI me likh k aega ki kya h ye
        required: true                               # mandatory h input dena isko ya ni
        type: environment                            # it can be choice, boolean
      secondVariableNameIsmeValueStoreHogiIsInputKi:
            description: please select chocolate or icecream     # jo UI me likh k aega ki kya h ye
            required: true                               # mandatory h input dena isko ya ni
            type: choice
            options:
              - chocolate
              - icecream   

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print the value of input
        run: |
          echo "value of input is: ${{ inputs.anyVariableNameIsmeValueStoreHogiIsInputKi }}"
        

