name: eventWorkflowDispatch
on: 
  workflow_dispatch:                                # isse front end me 1 run workflow ka button aa jaega
    inputs:                                         # we cn ask for the input from user in workflow dispatch
      anyVariableNameIsmeValueStoreHogiIsInputKi:
        description: please select a environment     # jo UI me likh k aega ki kya h ye
        required: true                               # mandatory h input dena isko ya ni
        type: boolean                            # it can be choice, boolean, environment
      secondVariableNameIsmeValueStoreHogiIsInputKi:
            description: please select chocolate or icecream     # jo UI me likh k aega ki kya h ye
            required: true                               # mandatory h input dena isko ya ni
            type: choice                                # for dropdown
            options: 
              - chocolate
              - icecream 
      thirdvariableNameIsmeValueStoreHogiIsInputKi::
            description: A boolean option
            required: false
            type: boolean                           # checkbox k liye
      fourthvariableNameIsmeValueStoreHogiIsInputKi::
                description: "Environment"
                type: environment
                required: true      # to create this type, Settings-> environment-> new environment -> give name say production
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print the value of input                   # to access value of input
        run: |
          echo "value of input is: ${{ inputs.anyVariableNameIsmeValueStoreHogiIsInputKi }}"   
        

